// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfwafbphpdxgyrafslbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmd2FmYnBocGR4Z3lyYWZzbGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjIwMDIsImV4cCI6MjA1ODEzODAwMn0.ZpLpQ98QH3kbfawIQpnO1Z2nUJcPR9ze6I3M5w_DTC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);